[package]
name = "twig"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
rmcp = { version = "0.8.2", features = ["transport-io"] }
tokio = { version = "1.48.0", features = ["full"] }
