[env]
_.file = '.env'

[tasks."dev:mcp"]
description = "Run MCP server and connect via inspector"
run = "npx @modelcontextprotocol/inspector cargo run -- start"

[tasks."dev:page"]
description = "Locally serve project webpage"
run = "uvx --with mkdocs-material mkdocs serve"
dir = "{{cwd}}/website"

[tools]
node = "lts"
uv = "latest"

[settings]
python.uv_venv_auto = true
